- careers.html
- css/careers.css
- css/style.css
- index.html
- js/contact.js
Reverts SyedImtiyaz-1/Precious-IT-Services#1
> Revert "Home page modified"

- main.css
> fixed the login button alignment with border

- .gitignore
- CONTRIBUTING.md
- index.html
- main.css
- main.js
This PR added the node_modules to the .gitignore for security purposes.
FIXES #20
> Added gitignore

- CONTRIBUTING.md
This repository is extremely beneficial to those who are just getting started in the field of open source. Thank you very much for helping us.
> Added my Name

- CONTRIBUTING.md
- Profiles/Mitesh_Rathod.md
I have read the ReadMe.md as I have noticed that you are telling to make your_name.md file in Profile directory but Profile directory is not present in your repo so I added.
Hope I helped you! 😊
> PR Request For Contribution 

- CONTRIBUTING.md
- Profiles/Jenil_Gajjar.md
I have contributed as a part of **hacktoberfest**. 
Can you please add the **hacktoberfest** label?
I have updated the **CONTRIBUTING.md** file by adding my name and place. I have also added the **Jenil_Gajjar.md** file in the profiles folder.
> update contributing.md and added jenil_gajjar.md file

- chatBot/style.css
I think it seems good now...please let me know if any more changes are required.
> Issue#53 resloved

- main.css
Contact form UI Update
[ui-upgrade]: UI Enhancement in the form section #72
https://drive.google.com/file/d/18zBb0L2oiunnTioUPHTwUUwzdOPIC1mP/view?usp=sharing
> [ui-upgrade]: UI Enhancement in the form section #72

- backend/public/index.html
- careers.html
Describe the Update
A clear and concise description of what the bug is.
Fixed the logo link which redirect directly to the home page when clicked on it.
To Reproduce
Steps to reproduce the behavior:
Example for Projects page but this BUG is on every page
Go to 'Projects '
Click on 'Logo'
It will redirect to Homepage
Additional context
Add any other context about the problem here.
> [FIXED]: Updated Link for Logo 

- main.css
Resolve Text-transform Issue
Format Text of Description and Mail id to Normal #82
**check out**
https://drive.google.com/file/d/1d3MP64L89Cx0Hou2rTEUnDYfuhZaqgR-/view?usp=drive_link
https://drive.google.com/file/d/1gh-4xNk-5iSTW4eG32QoO3RHc62pmX1I/view?usp=drive_link
> Format Text of Description and Mail id to Normal #82

- CONTRIBUTING.md
- main.css
Closes #72 
This pull request addresses a UI issue where the map and form elements are vertically aligned, resulting in poor visibility and a compressed appearance of the map at the top of the form. The proposed changes aim to enhance the UI layout by aligning the map and the form elements horizontally. Additionally, this pull request makes the form section responsive for an improved user experience across various devices.
- Adjusted CSS styles to horizontally align the map and form elements.
- Fine-tuned margins and padding to ensure a balanced appearance.
- Implemented responsive design principles to enhance usability on different devices.
- Utilized media queries to adapt the layout for tablets, mobile devices, and other screens.
1) …
> Enhancing UI Layout and Responsiveness of Form Section

- careers.html
- css/careers.css
- js/carrers.js
Replaced Footer UI on Careers Page
> Replaced Footer UI on Careers Page

- CONTRIBUTING.md
- backend/public/style.css
- index.html
- main.css
Enhance
Home Section & Latest projects section fix the height of cards in home section and add padding in icons and margin in latest projects and some better Box shadow and change the color of the button
> enahnce(Issue#79):home-latest-project-cards

- CONTRIBUTING.md
> new commit

- index.html
- main.css
Format the text styles and fix typos.
> Fix text format

- index.html
- main.js
@SyedImtiyaz-1  #issue99 Live counting in Home section
> feat-live-counting #issue99

- CONTRIBUTING.md
- index.html
- js/contact.js
- main.css
It's important to note that the current contact form in the project has several issues, including:
- It lacks any form of real-time validation, leaving users confused when they submit incomplete or incorrectly formatted data.
- The client-side validation puts unnecessary load on our sever, as it has to process invalid submissions.
For example, if we fill the form like this and attempt to submit it:
It will still accept it, and display this:
To address these issues, I have made the following changes:
- Implemented client-side validation using JavaScript to validate user input in real-time.
- Added validation rules for fields such as name, email address, subject, and message content.
- Displayed error messages next to the respective input fields when validation fails.
- Designed and styled …
> Add real-time validation in the contact form

- index.html
> Update login button text to 'Log In'

- CONTRIBUTING.md
- lib/bootstrap/css/bootstrap.css
- lib/bootstrap/css/bootstrap.min.css
card_ui done with having some spacing between them.
Before changes:
After Changes:
> Cards done

- CONTRIBUTING.md
Have formatted the links for better readability.
> Add Sarvesh's name in 'Contributing.md' file

- CONTRIBUTING.md
- css/careers.css
i have made changes in career.css file using media queries which fixes the alignment issue of the submit button
fixes #95
> Fixes  bug [#63] :Button in Careers page is not aligned properly #63

- CONTRIBUTING.md
- index.html
> Fix footer team button

- CONTRIBUTING.md
- index.html
- js/contact.js
fixes #108 
Working fine with my local machine.
Tasks done -
> Fixed the form.

- CONTRIBUTING.md
- backend/public/projects.js
Fixes #119 
This PR fixes the issue of scrolling after closing the popup by clicking on cross button.
> Scroll issue fix

- CONTRIBUTING.md
- backend/public/style.css
- index.html
- main.css
Some New User UI interaction features have been updated .
Review this PR. I have successfully made the proposed changes.
> The pop-Up feature is Added when, user hover over any product. [ui-upgrade]: . #33

- CONTRIBUTING.md
- backend/public/projects.js
This PR closes #122
See video below:
[screen-capture (5).webm](https://github.com/SyedImtiyaz-1/PreciousServices-/assets/87017319/b7bd9914-4f66-4e64-90b4-090e899bcbc9)
> #122 - Page stuck bug

- CONTRIBUTING.md
- backend/public/projects.js
Reverts SyedImtiyaz-1/PreciousServices-#128
> Revert "#122 - Page stuck bug"

- CONTRIBUTING.md
- backend/public/style.css
- index.html
- main.css
Reverts SyedImtiyaz-1/PreciousServices-#137
> Revert "The pop-Up feature is Added when, user hover over any product. [ui-upgrade]: . #33"

- css/careers.css
- index.html
- main.css
- main.js
> resolve issue #16

- CONTRIBUTING.md
- backend/public/index.html
- backend/public/ourTeam/index.html
- backend/public/ourTeam/ourTeam.css
> consistent-footer

- main.css
> Update main.css- .header .navbar ul button

- index.html
- main.css
fixed footer border design 
<br />
fixed contact form design :
> added few changes in css to make a balanced design

- index.html
- main.css
Reverts SyedImtiyaz-1/PreciousServices#146
> Revert "added few changes in css to make a balanced design"

- CONTRIBUTING.md
I have Added My name to contributing.md file
> Updated Contributors.md

- backend/public/style.css
- main.css
@SyedImtiyaz-1 I have fixed the overlap issue please merge it under hacktoberfest
Fixes #165 
Thank you
> overlap issue fixed

- backend/public/style.css
This is fix for [BUG]: Project Popup img rendering issue #169,
**Before**
**After**
> :bug: #169 Added aspect-ratio to Project Popup img

- index.html
- main.css
I have updated the styling of the login button in the mobile view, I changed the button color to grey from white
suggest if any other changes required @SyedImtiyaz-1 
updated screenshot:
please merge my changes
> Updatedlogin  button styling in the mobile view

- index.html
- login.css
- login.html
- login.js
Added a login form made  using html,css and javascript. Login form is now showing up on clicking the Login button
> Added a login form on clicking the login button on home page

- backend/public/ourTeam/index.html
- backend/public/ourTeam/ourTeam.css
- chatBot/style.css
- main.css
I have solved this issue by adding hover effects to the buttons.
> Solved #207

- main.css
made all letters in the email field small
fixed #230
> closed the capitalization of email

- CONTRIBUTING.md
- backend/public/ourTeam/index.html
- backend/public/ourTeam/ourTeam.css
- backend/public/ourTeam/ourTeam.js
well by the time I made changes , other people had already contributed and added the neccessary styling in footer as well as header, still I made some changes in its html which removes unnecessary repetition of font-awesome-icons lib , as well as addition of change in styles of header when page is scrolled in ourTeam.js
> Our team page modded

- index.html
- main.css
I Redesigned the dark-theme button, adding animation of sun to moon when slider shits from light to dark theme. Used gradient which matches the website's theme.
> Redesigning the Dark-theme button according to the UI of the website.

- CONTRIBUTING.md
I have updated the Contributing.md file as per the guidelines, kindly check and merge it.
> add my profile 

- css/careers.css
> Logo of Carrer Page is fixed

- index.html
Hello @SyedImtiyaz-1 ,
Added links - 👍
> Added mailto and tel in footer

- backend/public/style.css
I have change the good look to  the Project Page
https://github.com/SyedImtiyaz-1/GetTechProjects/assets/137484958/c779e54b-0f92-478c-9fcd-27628cbda449
> Change the Look of Project Page

- CONTRIBUTING.md
- Projects/Weather_Dashboard/index.html
- Projects/Weather_Dashboard/script.js
- Projects/Weather_Dashboard/styles.css
Solved issue #303
A screenshot is hereby attached
> Added Weather Dashboard Project- Solved issue #303

- index.html
> fixed copyright

- index.html
- main.js
- package-lock.json
- package.json
Closes #333
* Included the animated counter upon scrolling which will add a feather to this wonderful Precious IT Services project.
I have tested the code and it works well
https://github.com/SyedImtiyaz-1/GetTechProjects/assets/123291594/8e1b4202-a2a0-4f4b-a042-fa5df1115441
I have followed the Code of Conduct and Contributing Guidelines
Kindly add level labels for the issue #333
> Added animated counter

- index.html
- main.js
- package-lock.json
- package.json
Reverts SyedImtiyaz-1/GetTechProjects#364
I'm unmerging your PR which is also called reverting because the project is not visible you have to add the proejct in drive first of all then add the link, name and img in the `backend>public>proejcts.json` 👍🏻
> Revert "Added animated counter"

- CONTRIBUTING.md
- Projects/FoodRecipe-Finder/index.html
This is my project preview
#376 project . Please approve
> Added FoodRecipe Finder Project

- index.html
- main.css
I have added icons to anchor tags in navbar.
Please add GSSOC and level label and also assign me to this PR.
> icons added to anchor tags in navbar

- CONTRIBUTING.md
- main.css
Fixes: #412 
Solved the Issue and not map is visible properly
> Map is Not Visible Properly in The Contact Form #412

- backend/public/index.html
- backend/public/style.css
- index.html
- main.css
- main.js
> Added hovering effect on Search Projects Button In Projects Page

- backend/public/index.html
- backend/public/style.css
- index.html
- main.css
- main.js
> Implemented placeholder text for input fields and add hover effects to improve interactivity." 

- index.html
- main.css
Flexbox size issue solved by making all boxes similar dimensions.
before
after
> [ui-upgrade]: Home project section flexbox #407

- js/theme.js
Reverts SyedImtiyaz-1/GetTechProjects#539
> Revert "Fixed 🐞: Persist Dark Mode/Light Mode Preference Across Page Refreshes"

- index.html
- main.css
form fixed with shadows and other stuff 
please merge this PR
> Form Fixed 

- main.css
Added the customised scroll bar to the website .
Please review my pull request .
> Added customised scrollbar

- backend/public/style.css
I have added hovering effect on Search Projects Button In Projects Page.
Fixes #498
https://github.com/SyedImtiyaz-1/GetTechProjects/assets/130372618/1fdd96a8-a50b-4e18-a8a3-2e9ee9c8108a
> Fix:Search-Hover

- main.css
Fixed issue : #575 
before
after
> Corrected the Counter Page

- index.html
Added javascript file for contact form submission
Missing submission of contact form (Issue #666)
Now the form takes submission and display a confirmation message as soon as the form is submitted @SyedImtiyaz-1 please have a look.
> Missing submission of contact form (Issue #666)

- about.html
- main.css
Email Font: The email font has been corrected to ensure consistency and readability across all platforms.
Icons Added: I've added the necessary icons to enhance the visual appeal and functionality.
Footer Quotes: The quotes in the footer section have been updated to better align with our brand message.
> done the require

- FAQ.html
- about.html
- backend/public/index.html
- backend/public/style.css
- careers.html
- css/careers.css
- css/faq.css
- index.html
- main.css
- main.js
fixed issue: #754 
https://github.com/SyedImtiyaz-1/GetTechProjects/assets/137484958/ed819424-36a6-4199-9438-510addec735f
> Added Animated Cursor to All Pages

- CONTRIBUTING.md
- Projects/Resume-Builder/index.html
- Projects/Resume-Builder/scripts/app.js
- Projects/Resume-Builder/scripts/script.js
- Projects/Resume-Builder/src/style.css
The Resume Builder WebApp consists of the following features:
- It would make the resume building process a cakewalk!
- Just enter the details like, name, personal details, academic details, work experience, skills, etc and boom, the resume will be ready in just a click!
- Also, the user will be able to update the details dynamically, including adding or removing sections, update personal information, or update new skills that they've learnt.
- The users will also be able to view the live resume, while creating it.
More interestingly, the users will also be able to download their generated resume as PDF.
Fixes issue no. #699 
https://github.com/SyedImtiyaz-1/GetTechProjects/assets/138088550/f0c468bd-870b-4a87-9661-9ffca6da66f3
> Added Resume Builder WebApp project

- js/theme.js
Fixed bug: Dark mode gets turned off on refreshing page
Fixes issue #869
> Dark mode on reloading
